source 'https://rubygems.org'

gem 'activesupport'
gem 'async-websocket', '~>0.8.0'
gem 'celluloid-io'
gem 'dotenv'
gem 'httparty'
gem 'json'
gem 'puma'
gem 'rack-test'
gem 'rspec'
gem 'sinatra'
gem 'slack-ruby-bot'
gem 'vcr'
gem 'webmock'
